name: agent_001
description: A top down shooter game about Agent-001.
version: 0.1.0

publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.8.2
  mini_sprite: 0.1.0
  flame_mini_sprite: 0.0.1+2
  flame_audio: 2.0.5
  flutter_native_splash: 2.3.2
  pixel_border: 2.0.0-nullsafety.1

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: false
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: PressStartP2
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
