name: invert_me
description: A simple Flame game.
version: 0.1.0

publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.3.0
  mini_sprite: 0.0.1
  flame_mini_sprite: 0.0.1

dev_dependencies:
  flutter_lints: 2.0.1

flutter:
  uses-material-design: false
